/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shoraka Interview Mock API
 * Inquiry car using plate
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type InquiryResponseOwner = {
  full_name: string;
  /**
   * Matches 00[1-9]{8} in the mock generator
   * @pattern ^00[1-9]\d{8}$
   */
  national_id: string;
};

export interface InquiryResponse {
  /** Echoed query param (or "unknown" in mock if missing) */
  plate: string;
  brand: string;
  model: string;
  /** Past date (mock-generated) */
  make_date: string;
  owner: InquiryResponseOwner;
}

export interface Error {
  message: string;
}

export type InquiryCarByPlateParams = {
/**
 * Vehicle plate. Must match the mock server rule regex: ^\d{2}(?:[s|d|ا-ی])\d{3}-\d{2}$

 * @pattern ^\d{2}(?:[s|d|ا-ی])\d{3}-\d{2}$
 */
plate: string;
};

/**
 * @summary Inquiry car using plate
 */
export const inquiryCarByPlate = <TData = AxiosResponse<InquiryResponse>>(
    params: InquiryCarByPlateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/inquiry/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export type InquiryCarByPlateResult = AxiosResponse<InquiryResponse>
